import json
import random
import structlog
from datetime import datetime, timezone
from sqlalchemy import select, update
from sqlalchemy.ext.asyncio import AsyncSession

from src.config import settings
from src.core.skill.models import SkillModel
from src.core.skill.service import SkillService
from src.core.memory.rag_manager import rag_manager

logger = structlog.get_logger()


class ABTestingManager:
    """Manages skill version branching, A/B routing, telemetry collection, and promotion/cleanup."""

    def __init__(self, redis_client=None):
        self._redis = redis_client

    async def _get_redis(self):
        if self._redis is not None:
            return self._redis
        from src.core.governance.approval import approval_manager
        self._redis = await approval_manager._get_redis()
        return self._redis

    async def fork_grey_skill(self, parent_skill_id: str, new_prompt: str, session: AsyncSession) -> dict | None:
        """Create a grey/flywheel variant of an existing skill in DB and register in Redis."""
        try:
            skill_service = SkillService(session)
            parent = await skill_service.get_by_id(parent_skill_id)
            if not parent:
                logger.error("Parent skill not found for A/B fork", skill_id=parent_skill_id)
                return None

            # Generate new version and skill_id
            suffix = datetime.now(timezone.utc).strftime("%Y%m%d%H%M%S")
            variant_skill_id = f"{parent_skill_id}:flywheel:{suffix}"
            
            # Bump minor version for beta/grey
            version_parts = parent["version"].split(".")
            if len(version_parts) >= 3:
                try:
                    patch = int(version_parts[2])
                    new_version = f"{version_parts[0]}.{version_parts[1]}.{patch}-beta.flywheel"
                except ValueError:
                    new_version = f"{parent['version']}-beta.flywheel"
            else:
                new_version = f"{parent['version']}-beta.flywheel"

            # Create variant DB entity
            data = {
                "skill_id": variant_skill_id,
                "name": f"{parent['name']} (Flywheel Variant)",
                "version": new_version,
                "description": f"Autogenerated flywheel variant of {parent_skill_id}",
                "tags": parent["tags"],
                "trigger_patterns": parent["trigger_patterns"],
                "context_budget": parent["context_budget"],
                "required_tools": parent["required_tools"],
                "input_schema": parent["input_schema"],
                "output_schema": parent["output_schema"],
                "system_prompt": new_prompt,
                "risk_level": parent["risk_level"],
                "approval_required": parent["approval_required"],
                "estimated_tokens": parent["estimated_tokens"],
                "estimated_duration_sec": parent["estimated_duration_sec"],
                "workspace_path": parent["workspace_path"],
                "is_active": True
            }

            variant = await skill_service.create(data)
            logger.info("Created grey fork variant of skill", parent_id=parent_skill_id, variant_id=variant_skill_id)

            # Register A/B routing in Redis
            r = await self._get_redis()
            config_key = f"agentdeep:ab_config:{parent_skill_id}"
            config = {
                "variant_id": variant_skill_id,
                "weight": settings.ab_routing_weight
            }
            await r.set(config_key, json.dumps(config))
            
            # Initialize telemetry keys
            await r.hset(f"agentdeep:ab_telemetry:{parent_skill_id}", mapping={"success": 0, "total": 0, "spent_tokens": 0})
            await r.hset(f"agentdeep:ab_telemetry:{variant_skill_id}", mapping={"success": 0, "total": 0, "spent_tokens": 0})

            return variant

        except Exception as e:
            logger.error("Failed to fork grey skill", parent_id=parent_skill_id, error=str(e))
            return None

    async def get_routing_decision(self, parent_skill_id: str) -> str:
        """Route parent_skill_id to a grey variant or fallback to itself based on random choice."""
        if not settings.ab_testing_enabled:
            return parent_skill_id

        try:
            r = await self._get_redis()
            config_key = f"agentdeep:ab_config:{parent_skill_id}"
            data = await r.get(config_key)
            if not data:
                return parent_skill_id

            config = json.loads(data)
            variant_id = config.get("variant_id")
            weight = config.get("weight", settings.ab_routing_weight)

            # Roll the dice
            if random.random() < weight:
                logger.info("A/B routing hit: routing to variant", parent_id=parent_skill_id, variant_id=variant_id)
                return variant_id
        except Exception as e:
            logger.error("A/B routing decision error, falling back to original", parent_id=parent_skill_id, error=str(e))

        return parent_skill_id

    async def record_run_result(self, skill_id: str, success: bool, tokens: int, score: float | None = None):
        """Record success status, tokens, and multi-judge quality score in Redis telemetry."""
        try:
            r = await self._get_redis()
            telemetry_key = f"agentdeep:ab_telemetry:{skill_id}"
            
            success_inc = 1 if success else 0
            await r.hincrby(telemetry_key, "success", success_inc)
            await r.hincrby(telemetry_key, "total", 1)
            await r.hincrby(telemetry_key, "spent_tokens", tokens)
            
            if score is not None:
                # Accumulate the quality score using hincrbyfloat
                await r.hincrbyfloat(telemetry_key, "total_score", float(score))
            
            logger.info("Recorded A/B telemetry", skill_id=skill_id, success=success, tokens=tokens, score=score)
        except Exception as e:
            logger.error("Failed to record A/B telemetry", skill_id=skill_id, error=str(e))

    async def evaluate_and_promote(self, parent_skill_id: str, variant_id: str, session: AsyncSession, min_eval_runs: int = None) -> bool | None:
        """Evaluate if the grey variant is better than parent. If so, promote it. Otherwise discard it."""
        try:
            r = await self._get_redis()
            
            # Fetch variant metrics
            v_data = await r.hgetall(f"agentdeep:ab_telemetry:{variant_id}")
            if not v_data:
                logger.warning("No telemetry found for variant", variant_id=variant_id)
                return None
            
            v_total = int(v_data.get(b"total", b"0"))
            
            # Dynamic min runs override for lightweight mode/cold start
            if min_eval_runs is None:
                if getattr(settings, "system_mode", "full") == "lightweight":
                    min_eval_runs = 1
                else:
                    min_eval_runs = settings.ab_min_eval_runs
 
            if v_total < min_eval_runs:
                # Not enough runs to evaluate
                logger.info("A/B evaluation postponed: insufficient runs", variant_id=variant_id, current_runs=v_total, required=min_eval_runs)
                return None

            # Fetch parent metrics
            p_data = await r.hgetall(f"agentdeep:ab_telemetry:{parent_skill_id}")
            p_total = int(p_data.get(b"total", b"0")) if p_data else 0
            
            v_success = int(v_data.get(b"success", b"0"))
            v_tokens = int(v_data.get(b"spent_tokens", b"0"))
            v_total_score = float(v_data.get(b"total_score", b"0.0"))
            
            p_success = int(p_data.get(b"success", b"0")) if p_data else 0
            p_tokens = int(p_data.get(b"spent_tokens", b"0")) if p_data else 0
            p_total_score = float(p_data.get(b"total_score", b"0.0")) if p_data else 0.0
            
            # Compute rates & averages
            v_rate = v_success / v_total
            p_rate = p_success / p_total if p_total > 0 else 0.0
            
            v_avg_tokens = v_tokens / v_total
            p_avg_tokens = p_tokens / p_total if p_total > 0 else 0.0

            v_avg_score = v_total_score / v_total
            p_avg_score = p_total_score / p_total if p_total > 0 else 0.0

            logger.info(
                "A/B Evaluation Details",
                parent=parent_skill_id, parent_success_rate=p_rate, parent_avg_tokens=p_avg_tokens, parent_avg_score=p_avg_score,
                variant=variant_id, variant_success_rate=v_rate, variant_avg_tokens=v_avg_tokens, variant_avg_score=v_avg_score
            )

            # High-fidelity Decision Matrix:
            # 1. Primary: Compare average Multi-Judge Score (avg_score).
            # 2. Secondary: If score diff is marginal (< 0.01), compare Success Rate (success_rate).
            # 3. Tertiary: If success rates are equal, compare Token efficiency (fewer tokens is better).
            should_promote = False
            score_diff = v_avg_score - p_avg_score

            if p_total == 0:
                # Cold start: Variant has runs but parent has none. Promote!
                should_promote = True
            elif score_diff > 0.01:
                # Variant performs logically better
                should_promote = True
            elif abs(score_diff) <= 0.01:
                # Marginal quality difference, check success rate
                if v_rate > p_rate:
                    should_promote = True
                elif v_rate == p_rate:
                    # Same quality and success rate, check token consumption efficiency
                    if v_avg_tokens < p_avg_tokens:
                        should_promote = True

            skill_service = SkillService(session)
            
            if should_promote:
                # Promote grey version
                variant_obj = await skill_service.get_by_id(variant_id)
                parent_obj = await skill_service.get_by_id(parent_skill_id)
                
                if variant_obj and parent_obj:
                    # Bump parent version (increment patch number)
                    version_parts = parent_obj["version"].split(".")
                    if len(version_parts) >= 3:
                        try:
                            patch = int(version_parts[2])
                            new_version = f"{version_parts[0]}.{version_parts[1]}.{patch + 1}"
                        except ValueError:
                            new_version = parent_obj["version"]
                    else:
                        new_version = parent_obj["version"]

                    # Update parent with variant's prompt
                    await skill_service.update(parent_skill_id, {
                        "system_prompt": variant_obj["system_prompt"],
                        "version": new_version
                    })
                    logger.info("FLYHEEL PROMOTION: Variant promoted to main", parent_id=parent_skill_id, version=new_version)
            else:
                logger.info("FLYWHEEL DISCARD: Variant discarded due to inferior or equal performance", variant_id=variant_id)

            # Clean up: delete variant skill and Redis configs
            await skill_service.delete(variant_id)
            await r.delete(f"agentdeep:ab_config:{parent_skill_id}")
            await r.delete(f"agentdeep:ab_telemetry:{parent_skill_id}")
            await r.delete(f"agentdeep:ab_telemetry:{variant_id}")

            return should_promote

        except Exception as e:
            logger.error("Failed to evaluate and promote A/B test", parent_id=parent_skill_id, error=str(e))
            return None


# Global singleton instance
ab_manager = ABTestingManager()
