"""add multi tenancy and rbac tables

Revision ID: 010b086ea8c4
Revises: dcaf833e3083
Create Date: 2026-06-12 19:32:04.889839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '010b086ea8c4'
down_revision: Union[str, None] = 'dcaf833e3083'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_name'), 'tenants', ['name'], unique=True)
    
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    
    # 1. Create default tenant
    default_tenant_id = '00000000-0000-0000-0000-000000000000'
    op.execute(
        f"INSERT INTO tenants (id, name, created_at) VALUES ('{default_tenant_id}', 'Default Tenant', NOW()) ON CONFLICT DO NOTHING"
    )

    # Drop foreign key constraint on tasks table first to avoid dependency block
    op.drop_constraint('tasks_skill_id_fkey', 'tasks', type_='foreignkey')

    # 2. Add columns as nullable first
    op.add_column('audit_logs', sa.Column('tenant_id', sa.UUID(), nullable=True))
    op.add_column('roles', sa.Column('tenant_id', sa.UUID(), nullable=True))
    op.add_column('scheduled_tasks', sa.Column('tenant_id', sa.UUID(), nullable=True))
    op.add_column('skills', sa.Column('tenant_id', sa.UUID(), nullable=True))
    op.add_column('tasks', sa.Column('tenant_id', sa.UUID(), nullable=True))

    # 3. Populate existing rows with default tenant ID
    op.execute(f"UPDATE audit_logs SET tenant_id = '{default_tenant_id}' WHERE tenant_id IS NULL")
    op.execute(f"UPDATE roles SET tenant_id = '{default_tenant_id}' WHERE tenant_id IS NULL")
    op.execute(f"UPDATE scheduled_tasks SET tenant_id = '{default_tenant_id}' WHERE tenant_id IS NULL")
    op.execute(f"UPDATE skills SET tenant_id = '{default_tenant_id}' WHERE tenant_id IS NULL")
    op.execute(f"UPDATE tasks SET tenant_id = '{default_tenant_id}' WHERE tenant_id IS NULL")

    # 4. Alter columns to be NOT NULL
    op.alter_column('audit_logs', 'tenant_id', nullable=False)
    op.alter_column('roles', 'tenant_id', nullable=False)
    op.alter_column('scheduled_tasks', 'tenant_id', nullable=False)
    op.alter_column('skills', 'tenant_id', nullable=False)
    op.alter_column('tasks', 'tenant_id', nullable=False)

    # 5. Create indices, foreign keys, unique constraints
    op.create_index(op.f('ix_audit_logs_tenant_id'), 'audit_logs', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'audit_logs', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    
    op.drop_index(op.f('ix_roles_role_id'), table_name='roles')
    op.create_index(op.f('ix_roles_role_id'), 'roles', ['role_id'], unique=False)
    op.create_index(op.f('ix_roles_tenant_id'), 'roles', ['tenant_id'], unique=False)
    op.create_unique_constraint('uq_roles_tenant_role_id', 'roles', ['tenant_id', 'role_id'])
    op.create_foreign_key(None, 'roles', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    
    op.drop_constraint('scheduled_tasks_name_key', 'scheduled_tasks', type_='unique')
    op.create_index(op.f('ix_scheduled_tasks_tenant_id'), 'scheduled_tasks', ['tenant_id'], unique=False)
    op.create_unique_constraint('uq_scheduled_tasks_tenant_name', 'scheduled_tasks', ['tenant_id', 'name'])
    op.create_foreign_key(None, 'scheduled_tasks', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    
    op.drop_constraint('skills_skill_id_key', 'skills', type_='unique')
    op.create_index(op.f('ix_skills_skill_id'), 'skills', ['skill_id'], unique=False)
    op.create_index(op.f('ix_skills_tenant_id'), 'skills', ['tenant_id'], unique=False)
    op.create_unique_constraint('uq_skills_tenant_skill_id', 'skills', ['tenant_id', 'skill_id'])
    op.create_foreign_key(None, 'skills', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')

    op.create_index(op.f('ix_tasks_tenant_id'), 'tasks', ['tenant_id'], unique=False)
    op.create_foreign_key('tasks_tenant_id_fkey', 'tasks', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('tasks_skill_id_fkey', 'tasks', 'skills', ['tenant_id', 'skill_id'], ['tenant_id', 'skill_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tasks_skill_id_fkey', 'tasks', type_='foreignkey')
    op.drop_constraint('tasks_tenant_id_fkey', 'tasks', type_='foreignkey')
    op.drop_index(op.f('ix_tasks_tenant_id'), table_name='tasks')
    op.drop_column('tasks', 'tenant_id')

    op.drop_constraint(None, 'skills', type_='foreignkey')
    op.drop_constraint('uq_skills_tenant_skill_id', 'skills', type_='unique')
    op.drop_index(op.f('ix_skills_tenant_id'), table_name='skills')
    op.drop_index(op.f('ix_skills_skill_id'), table_name='skills')
    op.create_unique_constraint('skills_skill_id_key', 'skills', ['skill_id'])
    op.drop_column('skills', 'tenant_id')

    # Recreate the old single-column foreign key on tasks pointing to skills(skill_id)
    op.create_foreign_key('tasks_skill_id_fkey', 'tasks', 'skills', ['skill_id'], ['skill_id'], ondelete='CASCADE')

    op.drop_constraint(None, 'scheduled_tasks', type_='foreignkey')
    op.drop_constraint('uq_scheduled_tasks_tenant_name', 'scheduled_tasks', type_='unique')
    op.drop_index(op.f('ix_scheduled_tasks_tenant_id'), table_name='scheduled_tasks')
    op.create_unique_constraint('scheduled_tasks_name_key', 'scheduled_tasks', ['name'])
    op.drop_column('scheduled_tasks', 'tenant_id')
    
    op.drop_constraint(None, 'roles', type_='foreignkey')
    op.drop_constraint('uq_roles_tenant_role_id', 'roles', type_='unique')
    op.drop_index(op.f('ix_roles_tenant_id'), table_name='roles')
    op.drop_index(op.f('ix_roles_role_id'), table_name='roles')
    op.create_index(op.f('ix_roles_role_id'), 'roles', ['role_id'], unique=True)
    op.drop_column('roles', 'tenant_id')
    
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.drop_index(op.f('ix_audit_logs_tenant_id'), table_name='audit_logs')
    op.drop_column('audit_logs', 'tenant_id')
    
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_table('users')
    
    op.drop_index(op.f('ix_tenants_name'), table_name='tenants')
    op.drop_table('tenants')
    # ### end Alembic commands ###
