"""Add_roles_skills_scheduler

Revision ID: c9709d79a498
Revises: 05abe44bc47d
Create Date: 2026-06-12 17:17:52.412954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c9709d79a498'
down_revision: Union[str, None] = '05abe44bc47d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('skills', 'tags',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=postgresql.ARRAY(sa.String()),
               nullable=False,
               existing_server_default=sa.text("'{}'::text[]"))
    op.alter_column('skills', 'trigger_patterns',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=postgresql.ARRAY(sa.String()),
               nullable=False,
               existing_server_default=sa.text("'{}'::text[]"))
    op.alter_column('skills', 'context_budget',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('8000'))
    op.alter_column('skills', 'required_tools',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=postgresql.ARRAY(sa.String()),
               nullable=False,
               existing_server_default=sa.text("'{}'::text[]"))
    op.alter_column('skills', 'input_schema',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('skills', 'output_schema',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('skills', 'risk_level',
               existing_type=sa.VARCHAR(length=16),
               nullable=False,
               existing_server_default=sa.text("'low'::character varying"))
    op.alter_column('skills', 'approval_required',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('skills', 'estimated_tokens',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('10000'))
    op.alter_column('skills', 'estimated_duration_sec',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('120'))
    op.alter_column('skills', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('skills', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('skills', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_skills_tags'), table_name='skills', postgresql_using='gin')
    op.create_index(op.f('ix_skills_workspace_path'), 'skills', ['workspace_path'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_skills_workspace_path'), table_name='skills')
    op.create_index(op.f('idx_skills_tags'), 'skills', ['tags'], unique=False, postgresql_using='gin')
    op.alter_column('skills', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('skills', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('skills', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('skills', 'estimated_duration_sec',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('120'))
    op.alter_column('skills', 'estimated_tokens',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('10000'))
    op.alter_column('skills', 'approval_required',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('skills', 'risk_level',
               existing_type=sa.VARCHAR(length=16),
               nullable=True,
               existing_server_default=sa.text("'low'::character varying"))
    op.alter_column('skills', 'output_schema',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('skills', 'input_schema',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('skills', 'required_tools',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               nullable=True,
               existing_server_default=sa.text("'{}'::text[]"))
    op.alter_column('skills', 'context_budget',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('8000'))
    op.alter_column('skills', 'trigger_patterns',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               nullable=True,
               existing_server_default=sa.text("'{}'::text[]"))
    op.alter_column('skills', 'tags',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               nullable=True,
               existing_server_default=sa.text("'{}'::text[]"))
    # ### end Alembic commands ###
