"""add_hash_and_previous_hash_to_audit_logs

Revision ID: f1b03dc2e402
Revises: 010b086ea8c4
Create Date: 2026-06-23 18:23:14.250609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f1b03dc2e402'
down_revision: Union[str, None] = '010b086ea8c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('previous_hash', sa.String(length=64), nullable=True))
    op.add_column('audit_logs', sa.Column('hash', sa.String(length=64), nullable=True))
    op.add_column('scheduled_tasks', sa.Column('last_run_time', sa.DateTime(timezone=True), nullable=True))
    op.add_column('scheduled_tasks', sa.Column('last_run_status', sa.String(length=64), nullable=True))
    op.alter_column('skills', 'input_schema',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('skills', 'output_schema',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('skills', 'output_schema',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('skills', 'input_schema',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_column('scheduled_tasks', 'last_run_status')
    op.drop_column('scheduled_tasks', 'last_run_time')
    op.drop_column('audit_logs', 'hash')
    op.drop_column('audit_logs', 'previous_hash')
    # ### end Alembic commands ###
